package com.gabriel.crypto_sys.ui.activity

import android.app.Application
import android.util.Log
import com.gabriel.crypto_sys.data.local.coin.dao.CoinDao
import com.gabriel.crypto_sys.data.local.coin.model.Coin
import com.gabriel.crypto_sys.utils.di.*
import com.google.firebase.FirebaseApp
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers.IO
import kotlinx.coroutines.launch
import org.koin.android.ext.android.inject
import org.koin.android.ext.koin.androidContext
import org.koin.core.context.startKoin

class CryptoApplication : Application() {

    private val dao: CoinDao by inject()

    override fun onCreate() {
        super.onCreate()
        FirebaseApp.initializeApp(this)

        startKoin {
            androidContext(this@CryptoApplication)
            modules(
                listOf(
                    firebaseModule,
                    localModules,
                    remoteModules,
                    repositorysModules,
                    viewModelModules
                )
            )
        }

        CoroutineScope(IO).launch {
            salvaCoin()
        }
    }

    private suspend fun salvaCoin() {
        try {
            dao.salvaCoin(
                Coin(cod = "AAVE", title = "Aave"),
                Coin(cod = "ACH", title = "Alchemy Pay"),
                Coin(cod = "ACMFT", title = "AC Milan"),
                Coin(cod = "ACORDO01", title = "None"),
                Coin(cod = "ADA", title = "Cardano"),
                Coin(cod = "ADS", title = "Adshares"),
                Coin(cod = "AGIX", title = "SingularityNET"),
                Coin(cod = "AIOZ", title = "Aioz"),
                Coin(cod = "ALCX", title = "Alchemix"),
                Coin(cod = "ALGO", title = "Algorand"),
                Coin(cod = "ALICE", title = "MyNeighborAlice"),
                Coin(cod = "ALLFT", title = "Alliance"),
                Coin(cod = "ALPHA", title = "Alpha Venture Dao"),
                Coin(cod = "AMFT", title = "Aston Martin Cognizant"),
                Coin(cod = "AMP", title = "Amp"),
                Coin(cod = "ANKR", title = "ANKR"),
                Coin(cod = "ANT", title = "Aragon"),
                Coin(cod = "APE", title = "ApeCoin"),
                Coin(cod = "API3", title = "API3"),
                Coin(cod = "ARGFT", title = "Argentine Football Association"),
                Coin(cod = "ASRFT", title = "AS Roma"),
                Coin(cod = "ATLAS", title = "Star Atlas"),
                Coin(cod = "ATMFT", title = "Fan Token ATM"),
                Coin(cod = "ATOM", title = "Cosmos"),
                Coin(cod = "AUDIO", title = "Audius"),
                Coin(cod = "AVAX", title = "Avalanche"),
                Coin(cod = "AXS", title = "Axie Infinity"),
                Coin(cod = "BADGER", title = "Badger DAO"),
                Coin(cod = "BAL", title = "Balancer"),
                Coin(cod = "BAND", title = "Band Protocol"),
                Coin(cod = "BARFT", title = "FC Barcelona"),
                Coin(cod = "BAT", title = "Basic Attention token"),
                Coin(cod = "BCH", title = "Bitcoin Cash"),
                Coin(cod = "BICO", title = "Biconomy"),
                Coin(cod = "BLZ", title = "Bluzelle"),
                Coin(cod = "BNT", title = "BANCOR"),
                Coin(cod = "BTC", title = "Bitcoin"),
                Coin(cod = "BTRST", title = "Braintrust"),
                Coin(cod = "CAIFT", title = "Fan Token CAI"),
                Coin(cod = "CEEK", title = "CEEK VR"),
                Coin(cod = "CHZ", title = "Chiliz"),
                Coin(cod = "CITYFT", title = "Manchester City FC"),
                Coin(cod = "CLV", title = "Clover Finance"),
                Coin(cod = "COMP", title = "Compound"),
                Coin(cod = "COTI", title = "COTI"),
                Coin(cod = "CRV", title = "Curve Dao Token"),
                Coin(cod = "CSCONS01", title = "Consorcio CS01"),
                Coin(cod = "CSCONS02", title = "Consorcio CS02"),
                Coin(cod = "CSCONS03", title = "Consórcio CS03"),
                Coin(cod = "CSCONS04", title = "Consorcio CS04"),
                Coin(cod = "CSCONS05", title = "Consorcio CS05"),
                Coin(cod = "CTSI", title = "Cartesi"),
                Coin(cod = "CVC", title = "Civic"),
                Coin(cod = "CVX", title = "Convex Finance"),
                Coin(cod = "DAI", title = "Dai"),
                Coin(cod = "DG", title = "Decentral Games"),
                Coin(cod = "DIA", title = "DIA"),
                Coin(cod = "DOGE", title = "Dogecoin"),
                Coin(cod = "DOT", title = "Polkadot"),
                Coin(cod = "DPI", title = "DeFi Pulse Index"),
                Coin(cod = "DYDX", title = "dYdX"),
                Coin(cod = "ENER01", title = "Token de Energia"),
                Coin(cod = "ENER02", title = "Energia 02"),
                Coin(cod = "ENER03", title = "Energia 03"),
                Coin(cod = "ENJ", title = "Enjin Coin"),
                Coin(cod = "ENS", title = "Ethereum Name Service"),
                Coin(cod = "ERN", title = "Ethernity"),
                Coin(cod = "ETH", title = "Ethereum"),
                Coin(cod = "FARM", title = "Harvest Finance"),
                Coin(cod = "FET", title = "Fetch.ai"),
                Coin(cod = "FIL", title = "Filecoin"),
                Coin(cod = "FLOKI", title = "Floki Inu"),
                Coin(cod = "FLOW", title = "Flow"),
                Coin(cod = "FTM", title = "None"),
                Coin(cod = "GALA", title = "Gala"),
                Coin(cod = "GALFT", title = "Galatasaray"),
                Coin(cod = "GALOFT", title = "Clube Atletico Mineiro"),
                Coin(cod = "GHST", title = "Aavegotchi"),
                Coin(cod = "GMT", title = "STEPN"),
                Coin(cod = "GNO", title = "Gnosis"),
                Coin(cod = "GODS", title = "Gods Unchained"),
                Coin(cod = "GRT", title = "The Graph"),
                Coin(cod = "GST", title = "Green Satoshi Token"),
                Coin(cod = "HIGH", title = "Highstreet"),
                Coin(cod = "HNT", title = "None"),
                Coin(cod = "HOT", title = "Holo"),
                Coin(cod = "ICP", title = "Internet Computer"),
                Coin(cod = "ILV", title = "Illuvium"),
                Coin(cod = "IMOB01", title = "None"),
                Coin(cod = "IMOB02", title = "None"),
                Coin(cod = "IMX", title = "Immutable X'"),
                Coin(cod = "INTERFT", title = "Inter Milan"),
                Coin(cod = "JASMY", title = "JasmyCoin"),
                Coin(cod = "JUVFT", title = "Juventus"),
                Coin(cod = "KEEP", title = "Keep Network"),
                Coin(cod = "KNC", title = "Kyber Network"),
                Coin(cod = "KP3R", title = "Keep3rV1"),
                Coin(cod = "KSM", title = "Kusama"),
                Coin(cod = "LDO", title = "Lido DAO Token"),
                Coin(cod = "LINK", title = "Chainlink"),
                Coin(cod = "LOOKS", title = "LooksRare"),
                Coin(cod = "LPT", title = "Livepeer"),
                Coin(cod = "LQTY", title = "Liquity"),
                Coin(cod = "LRC", title = "Loopring"),
                Coin(cod = "LTC", title = "Litecoin"),
                Coin(cod = "MANA", title = "MANA (Decentraland)"),
                Coin(cod = "MATIC", title = "Polygon"),
                Coin(cod = "MBCCSH01", title = "Consorcio H01"),
                Coin(cod = "MBCCSH02", title = "Consorcio H02"),
                Coin(cod = "MBCCSH03", title = "Consorcio H03"),
                Coin(cod = "MBCCSH04", title = "Consorcio H04"),
                Coin(cod = "MBCCSH05", title = "Consorcio H05"),
                Coin(cod = "MBCCSH06", title = "Consorcio H06"),
                Coin(cod = "MBCONS01", title = "Cota de Consórcio 01"),
                Coin(cod = "MBCONS02", title = "Cota de Consórcio 02"),
                Coin(cod = "MBFP01", title = "None"),
                Coin(cod = "MBFP02", title = "None"),
                Coin(cod = "MBFP03", title = "Fluxo de Pagamento 03"),
                Coin(cod = "MBFP04", title = "Fluxo de pagamento 04"),
                Coin(cod = "MBFP05", title = "None"),
                Coin(cod = "MBFP06", title = "Fluxos de Pagamento 06"),
                Coin(cod = "MBFP07", title = "Fluxos de Pagamento 07"),
                Coin(cod = "MBFP08", title = "Fluxos de Pagamento 08"),
                Coin(cod = "MBFP09", title = "Fluxos de Pagamento 09"),
                Coin(cod = "MBFP10", title = "Fluxos de Pagamento 10"),
                Coin(cod = "MBFP11", title = "Fluxos de Pagamento 11"),
                Coin(cod = "MBFP12", title = "Fluxos de Pagamento 12"),
                Coin(cod = "MBPRK01", title = "Precatório MB SP01"),
                Coin(cod = "MBPRK02", title = "Precatório MB SP02"),
                Coin(cod = "MBPRK03", title = "Precatório MB BR03"),
                Coin(cod = "MBPRK04", title = "Precatório MB RJ04"),
                Coin(cod = "MBPRK05", title = "Fluxo de Pagamentos 5"),
                Coin(cod = "MBPRK06", title = "Precatorio MB BR06"),
                Coin(cod = "MBPRK07", title = "Precatorio MB SP07"),
                Coin(cod = "MBSANTOS01", title = "Token da Vila"),
                Coin(cod = "MBTKN01", title = "MB TOKEN"),
                Coin(cod = "MBVASCO01", title = "Vasco Token"),
                Coin(cod = "MC", title = "Merit Circle"),
                Coin(cod = "MCO2", title = "Moss Carbon Credit"),
                Coin(cod = "MENGOFT", title = "Flamengo"),
                Coin(cod = "METIS", title = "MetisDAO"),
                Coin(cod = "MINA", title = "Mina"),
                Coin(cod = "MIR", title = "Mirror Protocol"),
                Coin(cod = "MKR", title = "Maker"),
                Coin(cod = "MPL", title = "Maple"),
                Coin(cod = "MVI", title = "Metaverse Index"),
                Coin(cod = "NAVIFT", title = "Natus Vincere"),
                Coin(cod = "NFT00", title = "Vale do Outback de 100 reais"),
                Coin(cod = "NFT10", title = "Iasy Tata"),
                Coin(cod = "NFT11", title = "NFT Feirante Abaetetubense"),
                Coin(cod = "NFT12", title = "NFT Facas Feitas"),
                Coin(cod = "NFT13", title = "NFT Mandala Yawanawa - Mariri a roda 2"),
                Coin(cod = "NFT14", title = "Dodge Dart Sedan 1970 Verde Imperial"),
                Coin(cod = "NFT15", title = "Dodge Dart Coupe 1971 Vermelho Etrusco"),
                Coin(cod = "NFT16", title = "Dodge Charger LS 1974 White"),
                Coin(cod = "NFT17", title = "Dodge Charger LS 1974 Black"),
                Coin(cod = "NFT18", title = "Combo de Dodges"),
                Coin(cod = "NFT19", title = "Teleton"),
                Coin(cod = "NFT2", title = "NFT Protetores da Floresta"),
                Coin(cod = "NFT20", title = "Topa tudo por dinheiro"),
                Coin(cod = "NFT21", title = "De casa nova"),
                Coin(cod = "NFT22", title = "Onde tudo comecou"),
                Coin(cod = "NFT23", title = "Matriarca e Patriarca"),
                Coin(cod = "NFT24", title = "Surui Riqueza e Autenticidade"),
                Coin(cod = "NFT25", title = "Teoria do Caos"),
                Coin(cod = "NFT26", title = "Tartarugas do rio Guapore"),
                Coin(cod = "NFT27", title = "Viajantes de Asas"),
                Coin(cod = "NFT28", title = "Talvez ele toque o ceu"),
                Coin(cod = "NFT29", title = "Observador"),
                Coin(cod = "NFT3", title = "NFT Protetores da Floresta - Peixe Mandy"),
                Coin(cod = "NFT30", title = "Luta"),
                Coin(cod = "NFT31", title = "Futuro"),
                Coin(cod = "NFT32", title = "Construcao"),
                Coin(cod = "NFT33", title = "Protetores da Floresta -Territorio Ancestral"),
                Coin(cod = "NFT34", title = "Protetores da Floresta - Protectores de la vida"),
                Coin(cod = "NFT35", title = "Protetores da Floresta - Peixe Tucunare"),
                Coin(cod = "NFT36", title = "Protetores da Floresta - O que voce come"),
                Coin(cod = "NFT37", title = "Protetores da Floresta - 2"),
                Coin(cod = "NFT38", title = "Maneva - Album Mundo Novo"),
                Coin(cod = "NFT39", title = "Frontispicio #1"),
                Coin(cod = "NFT4", title = "NFT Error"),
                Coin(cod = "NFT40", title = "Frontispicio #2"),
                Coin(cod = "NFT41", title = "Frontispicio #3"),
                Coin(cod = "NFT42", title = "Anguereco"),
                Coin(cod = "NFT43", title = "Black Angel - #1"),
                Coin(cod = "NFT44", title = "Black Angel - #2"),
                Coin(cod = "NFT45", title = "Black Angel - #3"),
                Coin(cod = "NFT46", title = "Black Angel - #4"),
                Coin(cod = "NFT47", title = "Black Angel - #5"),
                Coin(cod = "NFT48", title = "Black Angel - #6"),
                Coin(cod = "NFT49", title = "Cryptoyabas - #1"),
                Coin(cod = "NFT5", title = "NFT Simulation"),
                Coin(cod = "NFT50", title = "Cryptoyabas - #2"),
                Coin(cod = "NFT51", title = "Cryptoyabas - #3"),
                Coin(cod = "NFT52", title = "Cryptoyabas - #4"),
                Coin(cod = "NFT53", title = "Cryptoyabas - #5"),
                Coin(cod = "NFT54", title = "Cryptoyabas - #6"),
                Coin(cod = "NFT55", title = "Cryptoyabas - #7"),
                Coin(cod = "NFT56", title = "Cryptoyabas - #8"),
                Coin(cod = "NFT57", title = "Cryptoyabas - #9"),
                Coin(cod = "NFT58", title = "Um chamado para descentralizacao - #1"),
                Coin(cod = "NFT59", title = "Um chamado para descentralizacao - #2"),
                Coin(cod = "NFT6", title = "NFT Cosmovisao Tupinamba da Amazonia"),
                Coin(cod = "NFT60", title = "Um chamado para descentralizacao - #3"),
                Coin(cod = "NFT61", title = "Um chamado para descentralizacao - #4"),
                Coin(cod = "NFT62", title = "Um chamado para descentralizacao - #5"),
                Coin(cod = "NFT63", title = "Um chamado para descentralizacao - #6"),
                Coin(cod = "NFT64", title = "Diva I"),
                Coin(cod = "NFT65", title = "Lua Nova em 12 por cento"),
                Coin(cod = "NFT66", title = "Lua Crescente em 49 por cento"),
                Coin(cod = "NFT67", title = "Desenho de agenda #1"),
                Coin(cod = "NFT68", title = "Desenho de agenda #2"),
                Coin(cod = "NFT69", title = "Desenho de agenda #3"),
                Coin(cod = "NFT7", title = "NFT Barbara Parawara"),
                Coin(cod = "NFT70", title = "Luar em 432 hertz"),
                Coin(
                    cod = "NFT71",
                    title = "'Dois mundos unidos pelo amor. Inspirado pelo amor no amor atraves do Metaverso' - Thayllane"
                ),
                Coin(cod = "NFT72", title = "'O Metaverso com personagens da Disney.' - Maria Vitoria"),
                Coin(cod = "NFT73", title = "'O mundo mais doce' - Larissa"),
                Coin(
                    cod = "NFT74",
                    title = "'Meu mini universo, com varios biomas diferentes' - Carlos Eduardo (Cadu)"
                ),
                Coin(cod = "NFT75", title = "'O Multiverso da Nike' - Luiz"),
                Coin(cod = "NFT76", title = "'Um Metaverso repleto de novos amigos' - Thomaz"),
                Coin(cod = "NFT77", title = ""),
                Coin(cod = "Metanima", title = "O mundo dos animais.' - Davi Batista"),
                Coin(cod = "NFT78", title = "'O Metaverso colorido e divertido' - Rebeca Maria"),
                Coin(cod = "NFT79", title = "'Um mundo novo, atraves dos oculos' - Deivid L."),
                Coin(cod = "NFT8", title = "NFT Liberdade de sentir"),
                Coin(cod = "NFT80", title = "'Um mundo colorido, onde a alegria nao acaba' - Ana Julia"),
                Coin(
                    cod = "NFT81",
                    title = "'Metaverso do PS3, se voce chegar na arvore, voce ganha todos' Daniel Batista"
                ),
                Coin(cod = "NFT82", title = "'Metaverso com muitas brincadeiras' Marcos Pedro"),
                Coin(cod = "NFT83", title = "'Metadoce, o mundo dos doces' Ana Bela"),
                Coin(cod = "NFT84", title = "'Um estranho gigante de um mundo distante' Luiz Miguel"),
                Coin(cod = "NFT85", title = "'Uma cidade feliz e outra triste' Anne Elis"),
                Coin(
                    cod = "NFT86",
                    title = "'O mundo em que voce pode ser o que voce quiser' Maikon Freire"
                ),
                Coin(cod = "NFT87", title = "'Um Metaverso com zumbis' Carlos Henrique"),
                Coin(cod = "NFT88", title = "'Um universo com muitos amigos e brincadeiras' Luiz Gustavo"),
                Coin(cod = "NFT89", title = "'Um Metaverso de Minecraft colorido' Pedro Gabriel"),
                Coin(cod = "NFT9", title = "NFT Pescaria"),
                Coin(cod = "NFT91", title = "NFT.Rio | Exposicao"),
                Coin(cod = "NFT92", title = "NFT.Rio | Talks e Masterclass"),
                Coin(cod = "NFTI", title = "NFT Index"),
                Coin(cod = "NFTOKN01", title = "Cesta de NFTs"),
                Coin(cod = "NODL", title = "Nodle"),
                Coin(cod = "OCEAN", title = "Ocean Protocol"),
                Coin(cod = "OGFT", title = "OG eSports"),
                Coin(cod = "OGN", title = "Origin Protocol"),
                Coin(cod = "OMG", title = "Omg Network"),
                Coin(cod = "OP", title = "Optimism"),
                Coin(cod = "OPUL", title = "Opulous"),
                Coin(cod = "OXT", title = "Orchid"),
                Coin(cod = "PAXG", title = "PAX Gold"),
                Coin(cod = "PERP", title = "Perpetual Protocol"),
                Coin(cod = "PFLFT", title = "Professional Fighters League"),
                Coin(cod = "PLA", title = "PlayDapp"),
                Coin(cod = "POLS", title = "Polkastarter"),
                Coin(cod = "POLY", title = "Polymath"),
                Coin(cod = "PORFT", title = "Portugal National Team FT"),
                Coin(cod = "POWR", title = "Power Ledger"),
                Coin(cod = "PSGFT", title = "Paris Saint-Germain"),
                Coin(cod = "QNT", title = "Quant"),
                Coin(cod = "RACA", title = "Radio Caca"),
                Coin(cod = "RAD", title = "Radicle"),
                Coin(cod = "RARE", title = "SuperRare"),
                Coin(cod = "RARI", title = "Rarible"),
                Coin(cod = "REN", title = "Ren"),
                Coin(cod = "REQ", title = "Request"),
                Coin(cod = "RLY", title = "Rally"),
                Coin(cod = "RNDR", title = "Render Token"),
                Coin(cod = "ROSE", title = "Oasis Network"),
                Coin(cod = "SACI", title = "Sport Club Internacional"),
                Coin(cod = "SAND", title = "The Sandbox"),
                Coin(cod = "SAUBERFT", title = "Alfa Romeo Racing ORLEN"),
                Coin(cod = "SCCPFT", title = "Corinthians"),
                Coin(cod = "SDAO", title = "SingularityDAO"),
                Coin(cod = "SHIB", title = "Shiba Inu"),
                Coin(cod = "SKL", title = "SKALE Network"),
                Coin(cod = "SLP", title = "Smooth Love Potion"),
                Coin(cod = "SNX", title = "Synthetix"),
                Coin(cod = "SOL", title = "Solana"),
                Coin(cod = "SPELL", title = "Spell Token"),
                Coin(cod = "SPFCFT", title = "SPFC"),
                Coin(cod = "SRM", title = "Serum"),
                Coin(cod = "STG", title = "Stargate FInance"),
                Coin(cod = "STORJ", title = "Storj"),
                Coin(cod = "STVFT", title = "Sint-Truidense Voetbalvereniging"),
                Coin(cod = "STX", title = "Stacks"),
                Coin(cod = "SUPER", title = "SuperFarm"),
                Coin(cod = "SUSHI", title = "SushiSwap"),
                Coin(cod = "SYN", title = "Synapse"),
                Coin(cod = "THFT", title = "Team Heretics"),
                Coin(cod = "TLM", title = "Alien Worlds"),
                Coin(cod = "TRB", title = "Tellor"),
                Coin(cod = "TRU", title = "TrueFi"),
                Coin(cod = "UFCFT", title = "UFC"),
                Coin(cod = "UMA", title = "Uma"),
                Coin(cod = "UNI", title = "Uniswap"),
                Coin(cod = "USDC", title = "USD Coin"),
                Coin(cod = "USDP", title = "Pax Dollar"),
                Coin(cod = "VERDAO", title = "Sociedade Esportiva Palmeiras"),
                Coin(cod = "VSPRK01", title = "Precatorio VS SP01"),
                Coin(cod = "WBTC", title = "Wrapped Bitcoin"),
                Coin(cod = "WBX", title = "WiBX"),
                Coin(cod = "WLUNA", title = "Wrapped LUNA Token"),
                Coin(cod = "XLM", title = "Stellar"),
                Coin(cod = "XRP", title = "XRP"),
                Coin(cod = "XTZ", title = "Tezos"),
                Coin(cod = "YBOFT", title = "BSC Young Boys"),
                Coin(cod = "YFI", title = "yearn.finance"),
                Coin(cod = "YGG", title = "Yield Guild Games"),
                Coin(cod = "ZRX", title = "0x"),
                Coin(cod = "FTBRL", title = "None")
            )
        } catch (e: Exception) {
            Log.e("salvaCoin", "salvaCoin: $e")
            throw e
        }
    }
}
